name: visual_graphs
description: "A Graph Algorithm visualizer"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flame: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  icons_launcher: ^2.1.7

flutter:
  uses-material-design: true
